### ISSUE TITLE
Error messages when loading in safari and chrome mobile view

### ISSUE THREAD

**Issue by chrismclarke** [stats4sd/Stats4SD-Resources-Site#123]
Would be good to get this figured out before launch. Possibly linked to:
https://stackoverflow.com/questions/43520535/class-constructor-polymerelement-cannot-be-invoked-without-new

**Comment by chrismclarke** [comment]
Android device simulators in chrome work after hard refresh, iphone simulation still shows error messages related to firebase-auth.js

**Comment by dave-mills** [comment]
Fixed (I think) by using the **build/es5-bundled** version instead of the **es6-unbundled**. (looked at [this guide](https://www.polymer-project.org/2.0/start/toolbox/deploy) as I'd forgotten how deploying worked). 

New version deployed to the demo site works fine on every device within arms reach of my desk. Can you check if you still get the errors on your end?

**Comment by dave-mills** [comment]
Although, I'm still getting firebase auth errors when I try to sign in, but that's happening on all browsers now...

**Comment by chrismclarke** [comment]
Yes, something definitely has gone wrong with the deployment, I'm getting a lot more errors than I used to. Rolling back for now.

**Comment by chrismclarke** [comment]
think auth message is problem with minifying (see #132), needs confirmation of fix and testing for any other problems

**Comment by chrismclarke** [comment]
@dave-mills , can you test current test or live version to see if you still get any? showing fine on chrome and firefox for me. Polymer also mentions possible mobile emulation errors here: https://www.polymer-project.org/2.0/docs/es6 so assume that's ok?

**Comment by dave-mills** [comment]
Live version looking good on my browsers. Nicely done :-)
